### ISSUE TITLE
Reading of trigger time?

### ISSUE THREAD

**Issue by ngbrown** [RecordEvolution/IMCtermite#10]
The .RAW file from IMC hardware is saving the timestamp in the `Cb` field:

```
|Cb,1, 117,1,0,    1,         1,         0,    105682,         0,    105682,1,  2.0000000000000000E-02,  1.3088283620799999E+09,;
```

value of `1.3088283620799999E+09` is seconds since 1980 (the date specified in the `|NT` field), or `2021-06-22 03:26:02.080000`.

However, it's not being read into the channel info:

```json
[
  {
    "uuid": "447",
    "name": "Engine_Speed",
    "comment": "FSR_PRP_206",
    "origin": "imc STUDIO 5.2 R15 (4/30/2020)@imc DEVICES 2.13R6 (5.5.2020)@imcDev__11111111",
    "description": "",
    "language-code": "0x0409",
    "codepage": "1252",
    "yname": "Engine_Speed",
    "yunit": "RPM",
    "significantbits": "16",
    "xname": "",
    "xunit": "s",
    "xstepwidth": "0.1",
    "xoffset": "0.02",
    "group": {
      "index": "-1",
      "name": "",
      "comment": ""
    }
  }
]
```

**Comment by mario-fink** [comment]
Thanks for bringing up the issue as a reminder to process the trigger time. In version 1.2.9 the output now looks like:
`[
    {
        "uuid": "348",
        "name": "pressure_Vacuum",
        "comment": "",
        "origin": "imc STUDIO 5.0 R10 (04.08.2017)@imc DEVICES 2.9R7 (25.7.2017)@imcDev__15190567",
        "description": "",
        "trigger-time": "2019-05-07T05:48:26",
        "language-code": "",
        "codepage": "",
        "yname": "pressure_Vacuum",
        "yunit": "mbar",
        "significantbits": "32",
        "xname": "",
        "xunit": "s",
        "xstepwidth": "0.005",
        "xoffset": "2044.03",
        "group": {
            "index": "-1",
            "name": "",
            "comment": ""
        }
    }
]
`
