### ISSUE TITLE
Build pre-compiled wheel files and upload to PyPI

### ISSUE THREAD

**Issue by ngbrown** [RecordEvolution/IMCtermite#11]
Not all users will have Visual Studio build tools (on Windows) already installed. If pre-compiled wheel (`.whl`) files were uploaded to pip, then they wouldn't need to build at install.

**Comment by ngbrown** [comment]
@mario-fink Thanks for working on this. It is still only attempting to load the source distribution for me. Does `cp39-cp39` mean the wheel will only download for Python 3.9? I'm currently using Python 3.6 because that's the compatible version that integrates with another program. Can you build for all currently supported versions of Python (3.6, 3.7, 3.8, 3.9)?

If a separate build is needed for each, you could use a GitHub action and [cibuildwheel](https://pypi.org/project/cibuildwheel/) to build each wheel file.

**Comment by mario-fink** [comment]
By now, on both Linux and Windows there are binary wheels available for most Python 3.x distributions. Let me know if you need any extra builds and I'll add them to the workflow....

**Comment by mario-fink** [comment]
ef5aaac25401a38bdd64c150e59d1859d7382e44
