### ISSUE TITLE
ydata wont get extracted - list full of zeros instead

### ISSUE THREAD

**Issue by christiankno** [RecordEvolution/IMCtermite#12]
I have a .dat file that follows the FAMOS format. (same as a raw file, as far as i know) 
Im trying extract the measurement data from this file into python without the use of the official software since I'm planning on automating this process to compare this measurements with other data.

the first lines of it are as follows:
```
|CF,2,1,1;|CK,1,3,1,1;
|NO,1,7,1,0,,0,;
|CG,1,5,1,1,1;
|CD,1,32,1.000000000000000E-2,1,1,s,0,0,0;
|NT,1,27, 1, 1,1980, 0, 0, 0.0000000;
|CC,1,3,1,1;
|CP,1,16,1,4,7,32,0,0,1,0;
|Cb,1,49,1,0,1,1,0,23472,0,23472,1,0.000000000000000E+0,0,;
|CR,1,15,0,0,0,1,5,m/min;
|CN,1,25,0,0,0,13,Drahtvorschub,0,;
|CS,1,23474,1,!?í?í?Ý? ... ;
```
> 

Its a long measurement, and transforming the data bytes as a sequence of 32 bit integers gives me a plot pretty similar to the one from the official software, but the proportions are off.

when i extract it using `imcraw=imc_termite.imctermite(b'file.dat')` and `channel=imcraw.get_channels(True)[0]`, then `channel['xdata']` contains a list with the data for the time (which wast directly stored as a sequence of numbers in the dat file), but `channel['ydata']` contains a list full with zeros.

Like this:
```
channel['xdata']==[0.00, 0.01, 0.02, 0.03, 0.04]
channel['xdata']==[0.0, 0.0, 0.0, 0.0, 0.0]
```

I know the xdata is actually stored in the dat file, since ive extracted it by reading every 4 bytes of data and transforming them to an int, and plotting them to compare them. but i dont know what values im missing to modify my extracted data to the original data
[gas_flow.dat.txt](https://github.com/RecordEvolution/IMCtermite/files/7176417/gas_flow.dat.txt) (its actually a .dat file, extension changed to allow upload)
[gas_flow_official_export.txt](https://github.com/RecordEvolution/IMCtermite/files/7176424/gas_flow_official_export.txt) (this is what the stored data should look like)
.

**Comment by mario-fink** [comment]
I just published version 1.2.12 that appears to fix this issue. Decoding your files with the new version gives me data that exactly matches your ` .export.txt ` file:
```>>> channels[0]['xdata'][:10]
[0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09]
>>> channels[0]['ydata'][:10]
[8.123157501, 8.152482986, 8.181808472, 8.093832016, 8.152482986, 8.152482986, 8.152482986, 8.064506531, 8.123157501, 8.093832016]```
It appears the meta-data (in particular the CR block) of the IMC file provides a (wrong?) rescaling factor = 0.0 which effectively annihilates the data. However, from now on, whenever the rescaling factor is zero it'll be reset to 1.0 , i.e. not rescaling the data at all.
