### ISSUE TITLE
Non critical key NT v2

### ISSUE THREAD

**Issue by Clint65** [RecordEvolution/IMCtermite#16]
Hello,

First, thanks for this library !
I'm using it in my python code.

I noticed that with some files, the trigger-nt time was not right. 
Seeing the "Warning non critical key NT2 will be ignored", I dig a little and found that by adding the NT key with a version=2, it solved my problem.
--> in imc_key.hpp:
key(false,"NT","timestamp of trigger 2",2)

I'm not sure why by adding this line it changes the way trigget-nt is decoded:

Without :
trigger-time-nt:    1970-01-01T01:00:00
trigger-time:       2012-07-28T05:42:33

With:
trigger-time-nt:    1980-01-01T00:00:00
trigger-time:       2022-07-28T04:42:33

Any chances that you make this change and publish the python lib ?

Thanks in advance,

Cyril

**Comment by mario-fink** [comment]
Hi Cyril,

please check out new version 2.0.4 that features version 2 of the non-critical key NT.

Best regards
Mario
