### ISSUE TITLE
Failed to open File

### ISSUE THREAD

**Issue by okantopcu** [RecordEvolution/IMCtermite#19]
I am using Anaconda and I already tried all examples which was shared within the IMC Master package. All of them is working without a problem. However, during the handling my own raw files, i noticed that both 'ipynb' and the raw file have to be placed under the same folder. I wonder whether it is possible to call the raw file from another directory, for example from desktop. If it is not clear i can provide more detailed information.

**Comment by Priyanka260895** [comment]
yes it is possible.for this provides full address for path like this
imctm = IMCtermite.imctermite(b"C:\Users\guptap15\Desktop\RAW\Measurement.raw")
