### ISSUE TITLE
ydata values are wrong

### ISSUE THREAD

**Issue by berghaeu** [RecordEvolution/IMCtermite#20]
When reading in a .raw file  the channel names and xdata come just as expected.
When accessing the ydata of these channels it gives just random numbers for all channels: `[-149.659155832, 95.820914973, 50.353051944, 95.900265519, -149.659155832, 95.820914973, 50.353051944,  ...]`.

By opening the file with FAMOS reader the values come as expected: `[21.12, 21.29, 21.11, 21.11, 21.13, 21.29, 21.11, ...]`.

However, there is one channel that was created in FAMOS by substracting two channels and integrating them. The values of this channel seem to come just fine.

**Comment by mario-fink** [comment]
Please check out version 2.0.7 as a fix to that issue.

**Comment by berghaeu** [comment]
Version 2.0.7 fixed that issue.
Thank you very much.
