### ISSUE TITLE
PIP Package without VERSION File

### ISSUE THREAD

**Issue by Earris** [RecordEvolution/IMCtermite#22]
Hallo Mario,

die aktuelle PIP version IMCtermite-2.0.7.tar.gz hat leider folgendes Problem:

in setup.cfg

`version = file: VERSION`

Leider fehlt das VERSION file.

da nur folgende Files enthalten sind:

IMCtermite.egg-info
lib
IMCtermite.cpp
IMCtermite.pxd
IMCtermite.pyx
LICENSE
MANIFEST.in
PKG-INFO
README.md
pyproject.toml
setup.cfg
setup.py

**Comment by mario-fink** [comment]
Hi Lucas,

probier mal bitte PIP Package Version 2.0.8 aus, das jetzt auch das VERSION File enthält.

**Comment by Earris** [comment]
Funktioniert jetzt.

Vielen Dank.
