### ISSUE TITLE
Incorrect Trigger time and units

### ISSUE THREAD

**Issue by chadtenpas** [RecordEvolution/IMCtermite#23]
I am getting trigger times that are 1 hour later than the calculated trigger times using imc FAMOS. Additionally, I am not getting the complete units from the .raw files. I am using µm/m for strain data, but am only receiving m/m. I am wondering if we cannot pass the greek alphabet through the module? If there is anything I can provide to help with these, please let me know!

Best,

Chad t.

**Comment by mario-fink** [comment]
To have a look at the problem, I would like to first reproduce the issue. Can you share a sample of your .raw files? The shifted trigger time is probably a missing offset and the wrong unit presumably related to the file encoding ...

**Comment by chadtenpas** [comment]
Yup, here is a sample file. 

Note: I was able to calculate the trigger time from the 'addtime' and 'xoffset' and it matched the actual trigger time calculated in imc FAMOS.

[2023-06-13 17-40-00 (2).zip](https://github.com/RecordEvolution/IMCtermite/files/11819882/2023-06-13.17-40-00.2.zip)

**Comment by mario-fink** [comment]
@chadtenpas Please check out v2.0.16 that fixes both the shifted trigger time and the encoding problem

**Comment by chadtenpas** [comment]
@mario-fink Thank you for the updates to the code. 

I hate to be that guy that comes back with an issue, but I updated my IMCtermite to 2.0.16. For some reason I am still unable to get Greek symbols to pass through. I am using the same sample set that I sent above.
