### ISSUE TITLE
Backend subprocess exited when trying to invoke build_wheel

### ISSUE THREAD

**Issue by chadtenpas** [RecordEvolution/IMCtermite#25]
I was trying to build the newest update package using setuptools and I am getting this error: 
> '* Building wheel...
> building on platform: win32
> C:\Users\ChadtenPas\AppData\Local\Temp\build-env-ilkkhi81\lib\site-packages\setuptools\config\expand.py:132: SetuptoolsWarning: File 'C:\\Users\\CHADTE~1\\AppData\\Local\\Temp\\build-via-sdist-g9winiys\\IMCtermite-2.0.9\\README.md' cannot be found
>   return '\n'.join(
> running bdist_wheel
> running build
> running build_ext
> building 'IMCtermite' extension
> creating build
> creating build\temp.win-amd64-cpython-310
> creating build\temp.win-amd64-cpython-310\Release
> "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\ChadtenPas\AppData\Local\Temp\build-env-ilkkhi81\include -IC:\Users\ChadtenPas\AppData\Local\Programs\Python\Python310\include -IC:\Users\ChadtenPas\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /EHsc /TpIMCtermite.cpp /Fobuild\temp.win-amd64-cpython-310\Release\IMCtermite.obj /EHsc /std:c++17
> IMCtermite.cpp
> C:\Users\ChadtenPas\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
> error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
> 
> ERROR Backend subprocess exited when trying to invoke build_wheel * Building wheel...
> building on platform: win32
> C:\Users\ChadtenPas\AppData\Local\Temp\build-env-ilkkhi81\lib\site-packages\setuptools\config\expand.py:132: SetuptoolsWarning: File 'C:\\Users\\CHADTE~1\\AppData\\Local\\Temp\\build-via-sdist-g9winiys\\IMCtermite-2.0.9\\README.md' cannot be found
>   return '\n'.join(
> running bdist_wheel
> running build
> running build_ext
> building 'IMCtermite' extension
> creating build
> creating build\temp.win-amd64-cpython-310
> creating build\temp.win-amd64-cpython-310\Release
> "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\ChadtenPas\AppData\Local\Temp\build-env-ilkkhi81\include -IC:\Users\ChadtenPas\AppData\Local\Programs\Python\Python310\include -IC:\Users\ChadtenPas\AppData\Local\Programs\Python\Python310\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.36.32532\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" /EHsc /TpIMCtermite.cpp /Fobuild\temp.win-amd64-cpython-310\Release\IMCtermite.obj /EHsc /std:c++17
> IMCtermite.cpp
> C:\Users\ChadtenPas\AppData\Local\Programs\Python\Python310\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
> error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
> 
> ERROR Backend subprocess exited when trying to invoke build_wheel

I noticed that bump to pypi failed at the build wheel stage as well. 
Do you have any insight to why this is happening? 

Thank you,

Chad t.

**Comment by mario-fink** [comment]
Hi Chad,

as a fix to issue #23 I introduced the conversion of any non UTF-8 codepage (like the CP-1252) to UTF-8. As a consequence any non-standard characters like i.a. greek letters are correctly displayed. However, the required "iconv" library is not found for windows during the build wheels stage of the pypi workflow.

**Comment by mario-fink** [comment]
@chadtenpas Please check out the windows build of the latest release v.2.0.16 of the PyPi package at https://pypi.org/project/IMCtermite/
